LDFLAGS += -L../../bin -ldarnit
CFLAGS += -g -Wall 

default:
	$(CC) $(CFLAGS) particle_test.c -o particle_test $(LDFLAGS)

clean:
	@echo " [ RM ] testapp/particle_test/particle_test"
	@rm -f particle_test
