default:
	cd darnit-stringtable && make
	cd darnit-mksprite && make
	cd darnit-fsimage && make

clean:	
	cd darnit-stringtable && make clean
	cd darnit-mksprite && make clean
	cd darnit-fsimage && make clean
